parameters:
    env(DB_VERSION): 5.6
    env(DATABASE_URL): mysql://yourwebdb:yourwebdb@db:3306/yourwebdb
    db_version: '%env(DB_VERSION)%'

doctrine:
    dbal:
        driver: 'pdo_mysql'
        server_version: '%db_version%'
        charset: utf8mb4
        url: '%env(resolve:DATABASE_URL)%'
        mapping_types:
          enum: string
        types:
            CurrencyType: App\DBAL\Types\CurrencyType
            ReviewSiteStatusType: App\DBAL\Types\ReviewSiteStatusType
            AdDisplayType: App\DBAL\Types\AdDisplayType
            FileFormatType: App\DBAL\Types\FileFormatType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
        filters:
            softdeleteable:
                class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                enabled: true
