easy_admin:
    site_name: 'YourWeb Management'
    entities:
#        # List the entity class name you want to manage
        - App\Entity\Website
#        - App\Entity\SocialSite
        - App\Entity\WebsiteCategory
