twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        review_site_service: '@App\Service\CryptoCurrencySiteService'
        exit_link_service: '@App\Service\OutboundLinkService'
