ARG APP_ENV
FROM yourweb-${APP_ENV}-php:latest as php

FROM nginx:alpine

LABEL maintainer = "Layton Everson <layton.everson@gmail.com>"

ARG CONFIGPATH
COPY "./${CONFIGPATH}/" /config/
COPY --from=php /var/www/app/ /var/www/app/

RUN cp /config/nginx/nginx.conf /etc/nginx/nginx.conf \
  && cp -a /config/nginx/sites/. /etc/nginx/sites-available/ \
  && rm -Rf /config

ARG APP_ENV
ARG DBURL
ARG PHP_UPSTREAM_CONTAINER=php
ARG PHP_UPSTREAM_PORT=9000
RUN sed -i "s|__DATABASE_URL__|${DBURL}|g" /etc/nginx/sites-available/default.conf \
    && sed -i "s|__APP_ENV__|${APP_ENV}|g" /etc/nginx/sites-available/default.conf \
  && apk update && apk upgrade \
    && apk add --no-cache bash \
    && adduser -D -H -u 1000 -s /bin/bash www-data \
  && echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf \
    && rm /etc/nginx/conf.d/default.conf \
    && chown -R www-data:www-data /var/www/app/var

CMD ["nginx"]

EXPOSE 80 443
