version: '3'

services:
  php:
    labels:
      online.yourweb.site: cryptocurrency
    build:
      context: ./
      dockerfile: Dockerfile-Php
      args:
        - CONFIGPATH=./docker/prod
    networks:
      - backend

  builder:
    image: yourweb-build
    build:
      context: ./
      dockerfile: Dockerfile-Builder
      args:
        - CONFIGPATH=./docker/dev
        - APP_ENV=${APP_ENV}
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - APP_ENV=${APP_ENV}

  web:
    build:
      context: ./
      dockerfile: Dockerfile-Web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  datavolume:
    driver: "local"
  mysqldev:
    driver: "local"
  mysqlprod:
    driver: "local"
