version: '3'
services:
  workspace:
    build:
      context: ./docker/workspace
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
        - CHROME_DRIVER_VERSION=${WORKSPACE_CHROME_DRIVER_VERSION}
        - NODE_VERSION=${WORKSPACE_NODE_VERSION}
        - YARN_VERSION=${WORKSPACE_YARN_VERSION}
        - TZ=${WORKSPACE_TIMEZONE}
    volumes:
      - ./:/var/www
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

  php-fpm:
    build:
      context: docker/php-fpm
      args:
        - INSTALL_XDEBUG=true
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    expose:
      - "9000"
    depends_on:
      - workspace
    extra_hosts:
      - "dockerhost:${DOCKER_HOST_IP}"
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG}
      - SYMFONY_ENV
    networks:
      - backend

  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=${NGINX_PHP_UPSTREAM_CONTAINER}
        - PHP_UPSTREAM_PORT=${NGINX_PHP_UPSTREAM_PORT}
      dockerfile: Dockerfile
    volumes:
      - ./var/log/nginx/log:/var/log/nginx
      - ./:/var/www
      - ./docker/nginx/sites:/etc/nginx/sites-available
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  redis:
    build: docker/redis
    volumes:
      - redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend

  mongo:
    build: docker/mongo
    ports:
      - "${MONGODB_PORT}:27017"
    volumes:
      - mongodb:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  redis:
    driver: local
  mongodb:
    driver: local
  applications:
    driver: local
