version: '3'

services:
  php:
    labels:
      online.yourweb.site: cryptocurrency
    build:
      context: ./
      dockerfile: Dockerfile-Php
      args:
        - CONFIGPATH=./docker/prod
    networks:
      - backend

  migration-util:
    image: yourweb-migration-util
    build:
      context: ./docker
      dockerfile: Dockerfile-DbUpdate
    depends_on:
      - php

  web:
    build:
      context: ./
      dockerfile: Dockerfile-Web
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - php
    networks:
      - frontend
      - backend

  db:
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    networks:
      - backend

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"

volumes:
  datavolume:
    driver: "local"
  mysqldev:
    driver: "local"
  mysqlprod:
    driver: "local"
