ARG APP_ENV
FROM yourweb-build:${APP_ENV}-latest as AppCode

FROM nginx:alpine

LABEL maintainer = "Layton Everson <layton.everson@gmail.com>"

ARG APP_ENV
COPY "./${APP_ENV}/" /config/
COPY --from=AppCode /app.tar.gz/ /var/www/

WORKDIR /var/www

ARG APP_SECRET
ARG MYSQL_USER
ARG MYSQL_PASSWORD
ARG MYSQL_HOST=db
ARG MYSQL_DATABASE
ARG MYSQL_PORT=3306
ARG DB_VERSION=5.6
ARG PHP_UPSTREAM_CONTAINER=php
ARG PHP_UPSTREAM_PORT=9000

RUN cp /config/nginx/nginx.conf /etc/nginx/nginx.conf \
  && cp -a /config/nginx/sites/. /etc/nginx/sites-available/ \
  && mkdir /etc/nginx/certs \
  && cp -a /config/nginx/certs/. /etc/nginx/certs/ \
  && chmod -R 066 /etc/nginx/certs/* \
  && tar -xvf app.tar.gz \
  && rm -Rf /config \
  && rm -f /app.tar.gz \
  ## Default.conf
  && sed -i "s|__APP_ENV__|${APP_ENV}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__APP_SECRET__|${APP_SECRET}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__MYSQL_USER__|${MYSQL_USER}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__MYSQL_PASSWORD__|${MYSQL_PASSWORD}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__MYSQL_HOST__|${MYSQL_HOST}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__MYSQL_DATABASE__|${MYSQL_DATABASE}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__MYSQL_PORT__|${MYSQL_PORT}|g" /etc/nginx/sites-available/default.conf \
  && sed -i "s|__DB_VERSION__|${DB_VERSION}|g" /etc/nginx/sites-available/default.conf \
  #default-ssl
  && sed -i "s|__APP_ENV__|${APP_ENV}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__APP_SECRET__|${APP_SECRET}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__MYSQL_USER__|${MYSQL_USER}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__MYSQL_PASSWORD__|${MYSQL_PASSWORD}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__MYSQL_HOST__|${MYSQL_HOST}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__MYSQL_DATABASE__|${MYSQL_DATABASE}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__MYSQL_PORT__|${MYSQL_PORT}|g" /etc/nginx/sites-available/default-ssl.conf \
  && sed -i "s|__DB_VERSION__|${DB_VERSION}|g" /etc/nginx/sites-available/default-ssl.conf \
  && apk update && apk upgrade \
  && apk add --no-cache bash \
  && adduser -D -H -u 1000 -s /bin/bash www-data \
  && echo "upstream php-upstream { server ${PHP_UPSTREAM_CONTAINER}:${PHP_UPSTREAM_PORT}; }" > /etc/nginx/conf.d/upstream.conf \
  && rm /etc/nginx/conf.d/default.conf \
  && chown -R www-data:www-data /var/www/app/var

CMD ["nginx"]

EXPOSE 80 443
