db:
  image: registry-intl.us-west-1.aliyuncs.com/cryptocurrency-yourweb-online/db
  container_name: db
  restart: always
  environment:
    - MYSQL_DATABASE=$dbname
    - MYSQL_PASSWORD=$dbpass
    - MYSQL_ROOT_PASSWORD=$dbpass
    - MYSQL_USER=$dbuser
    - 'constraint:default_node_group!=reserved'
  ports:
    - 3306:3306/tcp
  volumes:
    - mysqlprod:/var/lib/mysql:rw

php:
  image: registry-intl.us-west-1.aliyuncs.com/cryptocurrency-yourweb-online/php
  environment:
    - APP_ENV=$appenv
    - DATABASE_URL=mysql://$dbuser:$dbpass@db:3306/$dbname
  depends_on:
    - db
  container_name: php

web:
  image: registry-intl.us-west-1.aliyuncs.com/cryptocurrency-yourweb-online/web
  depends_on:
    - php
    - db
  environment:
    - DEVELOPMENT_MODE=false
    - WEB_HTTP=true
    - APP_ENV=$appenv
    - DATABASE_URL=mysql://$dbuser:$dbpass@db:3306/$dbname
    - APP_SECRET=$appsecret
  labels:
    aliyun.routing.port_80: web;http://cryptocurrency.yourweb.online/
    aliyun.global: "true"
  deploy:
    mode: global  # Run a container on each node.
    restart_policy:
      condition: on-failure
  ports:
    - 80:80/tcp
    - 443:443/tcp

migration-util:
  image: registry-intl.us-west-1.aliyuncs.com/cryptocurrency-yourweb-online/migration-util
  depends_on:
    - php
    - db
  environment:
    - APP_ENV=$appenv
    - DATABASE_URL=mysql://$dbuser:$dbpass@db:3306/$dbname
